# Generated by Django 4.1.7 on 2023-03-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_manager"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="firstName",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="lastName",
            new_name="last_name",
        ),
    ]
