# Generated by Django 4.1.7 on 2023-03-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_bookmanageruser_user_alter_profil_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="is_superadmin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=True),
        ),
    ]
