# Generated by Django 4.1.7 on 2023-03-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_is_superuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adminuser",
            old_name="degree",
            new_name="level",
        ),
        migrations.RemoveField(
            model_name="adminuser",
            name="experienceYears",
        ),
        migrations.RemoveField(
            model_name="adminuser",
            name="is_superadmin",
        ),
        migrations.AddField(
            model_name="adminuser",
            name="profession",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
