# Generated by Django 4.1.7 on 2023-03-29 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_rename_degree_adminuser_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ISADMIN",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bookmanageruser",
            name="AdminCreator",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmanager_created",
                to="accounts.adminuser",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
