# Generated by Django 4.1.7 on 2023-03-16 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_user_is_manager"),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="addBy",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books_of_a_user",
                to="accounts.bookmanageruser",
            ),
        ),
        migrations.AlterField(
            model_name="commandbooks",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="All_Commends_Of_A_User",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="validatecommands",
            name="validator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="All_Validated_Commands_Of_A_BookManagerUser",
                to="accounts.bookmanageruser",
            ),
        ),
    ]
