# Generated by Django 4.1.7 on 2023-03-17 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_user_is_manager"),
        ("books", "0002_alter_books_addby_alter_commandbooks_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="create_By",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manager_infos",
                to="accounts.bookmanageruser",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="commandbooks",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="All_Commends_Of_A_User",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="validatecommands",
            name="validator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="All_Validated_Commands_Of_A_BookManagerUser",
                to="accounts.bookmanageruser",
            ),
        ),
    ]
