# Generated by Django 4.1.7 on 2023-03-19 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_manager"),
        ("books", "0003_category_create_by_alter_commandbooks_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="create_By",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manager_infos",
                to="accounts.bookmanageruser",
            ),
        ),
    ]
