# Generated by Django 4.1.7 on 2023-03-29 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_user_isadmin_alter_user_is_manager"),
        ("books", "0004_alter_category_create_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="create_By",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manager_infos",
                to="accounts.bookmanageruser",
            ),
        ),
    ]
