# Generated by Django 4.1.7 on 2023-03-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_category_create_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
