# Generated by Django 4.1.7 on 2023-03-30 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0009_alter_user_isadmin_alter_user_is_manager"),
        ("books", "0006_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandbooks",
            name="bookId",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commands",
                to="books.books",
            ),
        ),
        migrations.AlterField(
            model_name="commandbooks",
            name="user",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Commends_Of_A_User",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="validatecommands",
            name="commandId",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validated",
                to="books.commandbooks",
            ),
        ),
        migrations.AlterField(
            model_name="validatecommands",
            name="validator",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="All_Validated_Commands_Of_A_BookManagerUser",
                to="accounts.bookmanageruser",
            ),
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="History_Commands_Of_this_Book",
                        to="books.books",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Older_commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="command_validated",
                        to="accounts.bookmanageruser",
                    ),
                ),
            ],
        ),
    ]
